<div class="wrapper">
    <div class="mini-carousel">
        <div class="mini-carousel-content">
            <i id="left" class="fa-solid fa-angle-left mini"></i>
            <ul class="carousels">
                <?php
                include 'miniCarousel.php';
                ?>
            </ul>
            <i id="right" class="fa-solid fa-angle-right mini"></i>
        </div>
        <script src="../../js/miniCarousel.js"></script>
    </div>
</div>