<div class="category-container">
    <div class="wrapper">
        <div class="category-list">
            <div class="tab-wrapper category-tab-wrapper">
                <ul class="nav nav-tabs category-nav-tab" id="myTab" role="tablist">
                    <?php
                    include "getCategory/category.php";
                    ?>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane active content-block" id="pills-s1">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s2">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s3">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s4">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s5">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s6">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s7">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s8">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s9">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'getCategory/categoryItems.php';
                                ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>