<div class="category-container">
    <div class="wrapper">
        <div class="category-list">
            <div class="tab-wrapper category-tab-wrapper">
                <ul class="nav nav-tabs category-nav-tab" id="myTab" role="tablist">
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link active" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s1"
                           type="button" role="tab" aria-controls="home" aria-selected="true">
                            <div>
                                Best Deals
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s2"
                           type="button" role="tab" aria-controls="profile" aria-selected="false">
                            <div>
                                TV & Video
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s3"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                Cameras
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s4"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                Audio
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s5"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                Smartphones
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s6"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                GPS & Navi
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s7"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                Computers
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s8"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                Portable Audio
                            </div>
                        </a>
                    </li>
                    <li class="nav-item category-nav-item" role="presentation">
                        <a class="nav-link category-nav-link" id="tab" data-bs-toggle="tab"
                           data-bs-target="#pills-s9"
                           type="button" role="tab" aria-controls="contact" aria-selected="false">
                            <div>
                                Accessories
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane active content-block" id="pills-s1">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'categoryItems.php';
                                ?>
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image8.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Smartphone 6S 32GB LTE</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image5.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Purple Solo 2 Wireless</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image6.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Smartphone 6S 32GB LTE</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image5.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <?php
                                include 'categoryItems.php';
                                ?>
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Widescreen NX Mini F1 SMART NX</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image4.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Full Color LaserJet Pro M452dn</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image3.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>GameConsole Destiny Special Edition</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image2.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
<!--                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">-->
<!--                                    <div class="category-product-list">-->
<!--                                        <div class="category-card-product">-->
<!--                                            <div class="product-type">-->
<!--                                                <a>Speakers</a>-->
<!--                                            </div>-->
<!--                                            <h5 class="product-name">-->
<!--                                                <a>Camera C430W 4k Waterproof</a>-->
<!--                                            </h5>-->
<!--                                            <div class="product-img">-->
<!--                                                <a>-->
<!--                                                    <img src="../images/image1.jpg">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="product-buy">-->
<!--                                                <div class="product-price">-->
<!--                                                    $685.00-->
<!--                                                </div>-->
<!--                                                <a>-->
<!--                                                    <div class="product-add-to-cart"><i-->
<!--                                                            class="fa-solid fa-cart-shopping"></i>-->
<!--                                                    </div>-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            <div class="card-hidden-items">-->
<!--                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>-->
<!--                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>-->
<!--                                            </div>-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </li>-->
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s2">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s3">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s4">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s5">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s6">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s7">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s8">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="tab-pane content-block" id="pills-s9">
                    <div class="category-card-content row">
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Wireless Audio System Multiroom 360 degree Full base audio</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image8.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Purple Solo 2 Wireless</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image6.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Smartphone 6S 32GB LTE</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image5.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="consoles-card col-md-6 col-xl-4 col-lg-6 col-sm-12">
                            <div class="consoles-card-container">
                                <div class="consoles-card-content">
                                    <div class="consoles-type">
                                        <a>Game Consoles</a>
                                    </div>
                                    <h5 class="consoles-name">
                                        <a>Game Console Controller + USB 3.0 Cable</a>
                                    </h5>
                                    <div class="consoles-img">
                                        <a>
                                            <img src="../images/consoles.jpg">
                                        </a>
                                        <div class="consoles-mini-img">
                                            <div class="mini-img-item1">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item2">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                            <div class="mini-img-item3">
                                                <div class="mini-image-loop">+</div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product-buy">
                                        <div class="product-price">
                                            $685.00
                                        </div>
                                        <a>
                                            <div class="consoles-add-to-cart">Add to Card</div>
                                        </a>
                                    </div>
                                    <div class="card-hidden-items">
                                        <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                        <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-list col-md-3 col-xl-4 col-lg-3 col-sm-12">
                            <ul class="row product-list-row flex-xl-row flex-md-column">
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Widescreen NX Mini F1 SMART NX</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image4.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Full Color LaserJet Pro M452dn</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image3.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>GameConsole Destiny Special Edition</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image2.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <li class="col-sm-12 col-md-12 col-xl-6 d-md-none d-lg-none d-xl-block product-list-col">
                                    <div class="category-product-list">
                                        <div class="category-card-product">
                                            <div class="product-type">
                                                <a>Speakers</a>
                                            </div>
                                            <h5 class="product-name">
                                                <a>Camera C430W 4k Waterproof</a>
                                            </h5>
                                            <div class="product-img">
                                                <a>
                                                    <img src="../images/image1.jpg">
                                                </a>
                                            </div>
                                            <div class="product-buy">
                                                <div class="product-price">
                                                    $685.00
                                                </div>
                                                <a>
                                                    <div class="product-add-to-cart"><i
                                                            class="fa-solid fa-cart-shopping"></i>
                                                    </div>
                                                </a>
                                            </div>
                                            <div class="card-hidden-items">
                                                <a><i class="fa-solid fa-code-compare"></i> Compare</a>
                                                <a><i class="fa-regular fa-heart"></i> Add to Wishlist</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>