<div class="wrapper">
    <div class="bestseller-container">
        <div class="bestseller-nav">
            <h3 class="bestseller-title">
                Bestsellers
            </h3>
            <ul class="bestseller-links">
                <li class="bestseller-link bestseller-top">
                    <a href="#">Top 20</a>
                </li>
                <li class="bestseller-link">
                    <a href="#">Phones & Tablets</a>
                </li>
                <li class="bestseller-link">
                    <a href="#">Laptops & Computers</a>
                </li>
                <li class="bestseller-link">
                    <a href="#">Video Cameras</a>
                </li>
            </ul>
        </div>
        <div class="bestseller-content">
            <div class="bestseller-cards">
                    <div class="slider bestseller-carousel-inner">
                        <div class="slid carousel-it bestseller-carousel-items">
                            <ul class="row bestseller-carousel-item">
                                <?php
                                include "bestseller.php";
                                ?>
                            </ul>
                        </div>
                        <div class="slid carousel-it bestseller-carousel-items">
                            <ul class="row bestseller-carousel-item">
                                <?php
                                include "bestseller.php";
                                ?>
                            </ul>
                        </div>
                        <div class="slid carousel-it bestseller-carousel-items">
                            <ul class="row bestseller-carousel-item">
                                <?php
                                include "bestseller.php";
                                ?>
                            </ul>
                        </div>
                    </div>
                    <div id="sliderDots"></div>
                    <script src="../../js/bestseller.js"></script>
            </div>
        </div>
        <div class="banner">
            <a href="#">
                <img src="../../images/banner.png">
            </a>
        </div>
    </div>
</div>
